apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nginx:1.26.1 # Image defined here
        ports:
        - containerPort: 80
        env:
        - name: SERVER_IP
          value: "default_ip"

